resources:
- repo: self

variables:
  ArtifactsDirectoryName: 'artifacts'
  BuildConfiguration: 'Debug'
  BuildPlatform: 'Any CPU'
  DotNet6Version: '6.x'
  DotNet7Version: '7.x'
  MSBuildArguments: '"/Property:Platform=$(BuildPlatform);Configuration=$(BuildConfiguration)" "/BinaryLogger:$(Build.SourcesDirectory)\$(ArtifactsDirectoryName)\msbuild.binlog"'

trigger:
  batch: 'true'
  branches:
    include:
    - 'main'
    - 'refs/tags/*'
  paths:
    exclude:
    - '*.md'
pr:
  branches:
    include:
    - 'main'
  paths:
    exclude:
    - '*.md'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  pool:
    vmImage: windows-latest
  steps:
  - script: 'echo ##vso[task.setvariable variable=BuildConfiguration;]Release'
    displayName: 'Set BuildConfiguration to Release for tagged commits'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))

  - task: UseDotNet@2
    displayName: 'Install .NET $(DotNet6Version)'
    inputs:
      version: '$(DotNet6Version)'

  - task: UseDotNet@2
    displayName: 'Install .NET $(DotNet7Version)'
    inputs:
      version: '$(DotNet7Version)'

  - task: MSBuild@1
    displayName: 'Build Solution'
    inputs:
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      msbuildArguments: '$(MSBuildArguments)'

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests (.NET Framework)'
    inputs:
      command: 'test'
      arguments: '--no-restore --no-build --configuration:$(BuildConfiguration) --framework net472 /noautorsp'
      testRunTitle: '.NET Framework v4.7.2'
    condition: succeededOrFailed()

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests (.NET 6.0)'
    inputs:
      command: 'test'
      arguments: '--no-restore --no-build --configuration:$(BuildConfiguration) --framework net6.0 /noautorsp'
      testRunTitle: '.NET 6.0'
    condition: succeededOrFailed()

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests (.NET 7.0)'
    inputs:
      command: 'test'
      arguments: '--no-restore --no-build --configuration:$(BuildConfiguration) --framework net7.0 /noautorsp'
      testRunTitle: '.NET 7.0'
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(ArtifactsDirectoryName)'
      ArtifactName: $(ArtifactsDirectoryName)
    condition: always()