resources:
- repo: self

variables:
  ArtifactsDirectoryName: 'artifacts'
  MSBuildArguments: '"/BinaryLogger:$(Build.SourcesDirectory)\$(ArtifactsDirectoryName)\msbuild.binlog"'
  BuildConfiguration: 'Debug'
  BuildPlatform: 'Any CPU'

pool:
  vmImage: 'windows-2019'
trigger:
  batch: true
  branches:
    include:
    - 'master'
    - 'refs/tags/*'
  paths:
    exclude:
    - '*.md'
pr:
  branches:
    include:
    - 'master'
  paths:
    exclude:
    - '*.md'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  pool:
    vmImage: windows-latest
  steps:
  - script: 'echo ##vso[task.setvariable variable=BuildConfiguration;]Release'
    displayName: 'Set BuildConfiguration to Release for tagged commits'
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))

  - task: MSBuild@1
    displayName: 'Build Solution'
    inputs:
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'
      msbuildArguments: '$(MSBuildArguments)'

  - task: VSTest@2
    displayName: 'Run Unit Tests'
    inputs:
      testAssemblyVer2: |
       **\*Tests.dll
       !**\obj\**
      platform: '$(BuildPlatform)'
      configuration: '$(BuildConfiguration)'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(ArtifactsDirectoryName)'
      ArtifactName: $(ArtifactsDirectoryName)
    condition: always()